defaults:
  - _self_

_target_: src.dataset.view_sampler.view_sampler_bounded_v2.ViewSamplerBoundedV2

cfg:
  name: boundedv2

  num_target_views: 6
  num_context_views: 4

  min_distance_between_context_views: 20
  max_distance_between_context_views: 50
  max_distance_to_context_views: 0

  context_gap_warm_up_steps: 10000
  target_gap_warm_up_steps: 0

  initial_min_distance_between_context_views: 15
  initial_max_distance_between_context_views: 30
  initial_max_distance_to_context_views: 0
  extra_views_sampling_strategy: farthest_point
  target_views_replace_sample: false